from environment import Grid3D

class FailureCase:
    def __init__(self, case_id, name, hypothesis, challenge, grid_size, start, goal, obstacles, manual_waypoints=None):
        self.case_id = case_id
        self.name = name
        self.hypothesis = hypothesis
        self.challenge = challenge
        self.grid_size = grid_size
        self.start = start
        self.goal = goal
        self.obstacles = obstacles
        self.manual_waypoints = manual_waypoints or []
        self.waypoint_variants = {}

    def get_env(self):
        env = Grid3D(self.grid_size)
        env.obstacles = set(self.obstacles)
        return env

def create_u_shape_trap():
    obstacles = []
    # U-shape opening to the left (negative x)
    for y in range(2, 9):
        obstacles.append((8, y, 2)) # base
    for x in range(4, 9):
        obstacles.append((x, 2, 2)) # bottom leg
        obstacles.append((x, 8, 2)) # top leg
    
    return FailureCase(
        case_id="A",
        name="U-shaped obstacle trap",
        hypothesis="A waypoint inside a concave obstacle will trap the search, leading to massive node expansions as the heuristic forces it against the wall.",
        challenge="Navigate out of a U-shaped local minimum.",
        grid_size=(15, 15, 5),
        start=(2, 5, 2),
        goal=(12, 5, 2),
        obstacles=obstacles,
        manual_waypoints=[(7, 5, 2)] # Inside the U-shape
    )

def create_misleading_waypoint():
    obstacles = []
    # Solid wall blocking direct path
    for y in range(0, 10):
        obstacles.append((5, y, 2))
    
    return FailureCase(
        case_id="B",
        name="Misleading waypoint behind a wall",
        hypothesis="A valid but geographcially inefficient waypoint forces a large detour, making LLM-A* expand more nodes and find a costlier path than standard A*.",
        challenge="Detour away from the goal.",
        grid_size=(10, 10, 5),
        start=(1, 5, 2),
        goal=(8, 5, 2),
        obstacles=obstacles,
        manual_waypoints=[(8, 1, 2)] # Far off to the side, behind the wall but requires going around the bottom
    )

def create_narrow_corridor():
    obstacles = []
    # Create a wide path at y >= 6, and a narrow zig-zag path at y <= 3
    for x in range(0, 10):
        obstacles.append((x, 4, 2))
    obstacles.append((4, 2, 2))
    obstacles.append((5, 1, 2))
    
    return FailureCase(
        case_id="C",
        name="Narrow corridor",
        hypothesis="Directing the search into a narrow, cluttered corridor increases search time compared to exploring a wide-open alternative.",
        challenge="Navigate a tight space instead of open space.",
        grid_size=(10, 10, 5),
        start=(1, 5, 2),
        goal=(8, 5, 2),
        obstacles=obstacles,
        manual_waypoints=[(4, 1, 2)] # Forces it into the narrow corridor
    )

def create_dead_end():
    obstacles = []
    # Dead end passage
    for x in range(2, 8):
        obstacles.append((x, 2, 2))
        obstacles.append((x, 4, 2))
    obstacles.append((7, 3, 2)) # cap the end
    
    return FailureCase(
        case_id="D",
        name="Dead-end waypoint",
        hypothesis="A waypoint deep inside a dead-end branch will force the search to explore useless space and backtrack.",
        challenge="Recover from a dead end.",
        grid_size=(10, 10, 5),
        start=(1, 1, 2),
        goal=(8, 8, 2),
        obstacles=obstacles,
        manual_waypoints=[(6, 3, 2)] # Inside the dead end
    )

def create_coarse_map_info_loss():
    # We create a map where the exact coordinates matter.
    # We will test this with LLM generation (using compact vs exact).
    obstacles = []
    for x in range(3, 7):
        for y in range(3, 7):
            obstacles.append((x, y, 2))
    # Leave a tiny hole at (5,5,2) that isn't really accessible, or a specific path
    
    return FailureCase(
        case_id="E",
        name="Coarse-map information loss",
        hypothesis="Compact density representation loses critical topological features, leading to poor waypoint generation.",
        challenge="LLM needs to generate waypoints, we compare prompt modes.",
        grid_size=(10, 10, 5),
        start=(1, 5, 2),
        goal=(8, 5, 2),
        obstacles=obstacles,
        manual_waypoints=[] # To be generated by LLM
    )

def create_bad_waypoint_ordering():
    return FailureCase(
        case_id="F",
        name="Bad waypoint ordering",
        hypothesis="Executing waypoints out of logical geometric order dramatically increases path cost and node expansions.",
        challenge="Zig-zagging across the map.",
        grid_size=(10, 10, 5),
        start=(1, 1, 2),
        goal=(8, 8, 2),
        obstacles=[],
        # Default is zig-zag
        manual_waypoints=[(8, 2, 2), (2, 8, 2), (7, 3, 2)]
    )
    case.waypoint_variants = {
        "sensible": [(3, 3, 2), (5, 5, 2), (7, 7, 2)],
        "reverse": [(7, 7, 2), (5, 5, 2), (3, 3, 2)],
        "zig-zag": [(8, 2, 2), (2, 8, 2), (7, 3, 2)]
    }
    return case

def create_clustered_obstacles():
    obstacles = []
    # Cluster 1
    for x in range(2, 4):
        for y in range(2, 4):
            obstacles.append((x, y, 2))
    # Cluster 2
    for x in range(6, 8):
        for y in range(6, 8):
            obstacles.append((x, y, 2))
            
    return FailureCase(
        case_id="G",
        name="Clustered obstacles",
        hypothesis="Waypoints placed near dense clusters pull the search into local minima, negating the benefit of heuristic guidance.",
        challenge="Avoid local minima around clusters.",
        grid_size=(10, 10, 5),
        start=(0, 0, 2),
        goal=(9, 9, 2),
        obstacles=obstacles,
        manual_waypoints=[(3, 4, 2), (7, 5, 2)] # Placed right next to clusters
    )

def create_3d_vertical_detour():
    obstacles = []
    # A massive wall in the XY plane, stretching from z=0 to z=3
    for x in range(0, 10):
        for y in range(4, 6):
            for z in range(0, 4):
                obstacles.append((x, y, z))
                
    return FailureCase(
        case_id="H",
        name="3D vertical detour",
        hypothesis="A strictly horizontal waypoint sequence will fail to utilize the vertical dimension, whereas standard A* will easily go over the wall.",
        challenge="Navigate in 3D over a barrier.",
        grid_size=(10, 10, 6),
        start=(5, 1, 1),
        goal=(5, 8, 1),
        obstacles=obstacles,
        manual_waypoints=[(5, 3, 1), (5, 7, 1)] # Horizontal waypoints that crash into the wall
    )

def create_repeated_target_switching():
    return FailureCase(
        case_id="I",
        name="Repeated target switching",
        hypothesis="Numerous sequential waypoints cause excessive O(N) reprioritizations of the OPEN set, slowing down search time relative to standard A* despite fewer node expansions.",
        challenge="Measure reprioritization overhead.",
        grid_size=(30, 30, 2),
        start=(0, 0, 0),
        goal=(29, 29, 0),
        obstacles=[],
        # Dense line of waypoints
        manual_waypoints=[(i, i, 0) for i in range(1, 28)]
    )

def create_no_path():
    obstacles = []
    # Bisect the map completely
    for y in range(0, 10):
        for z in range(0, 5):
            obstacles.append((5, y, z))
                
    return FailureCase(
        case_id="J",
        name="No-path and disconnected environment",
        hypothesis="The algorithm must correctly terminate and report failure rather than looping infinitely when no path exists.",
        challenge="Terminate correctly when disconnected.",
        grid_size=(10, 10, 5),
        start=(2, 2, 2),
        goal=(8, 8, 2),
        obstacles=obstacles,
        manual_waypoints=[(5, 5, 2)]
    )

ALL_CASES = [
    create_u_shape_trap(),
    create_misleading_waypoint(),
    create_narrow_corridor(),
    create_dead_end(),
    create_coarse_map_info_loss(),
    create_bad_waypoint_ordering(),
    create_clustered_obstacles(),
    create_3d_vertical_detour(),
    create_repeated_target_switching(),
    create_no_path()
]
